DROP TABLE LOG_MESSAGES_STARTED IF EXISTS;
DROP TABLE LOG_MESSAGES_FINISHED IF EXISTS;
DROP TABLE LONG_RUNING_MESSAGE IF EXISTS;
DROP TABLE BAD_RECORD_REPORT IF EXISTS;


CREATE TABLE LOG_MESSAGES_STARTED  (
    ID VARCHAR(30),    
    EVENT_TYPE VARCHAR(20),
    HOST VARCHAR(30),
    EVENT_TIME_STAMP BIGINT
);

CREATE TABLE LOG_MESSAGES_FINISHED (
    ID VARCHAR(30),    
    EVENT_TYPE VARCHAR(20),
    HOST VARCHAR(30),
    EVENT_TIME_STAMP BIGINT
);

CREATE TABLE BAD_RECORD_REPORT   (
    LINE_NUMBER BIGINT,
    ERROR_MESSAGE VARCHAR(100)    
);

